The *median* is the middle value in an ordered integer list. If the size of the list is even, there is no middle value, and the median is the mean of the two middle values.

- For example, for =arr = [2,3,4]=, the median is =3=.
- For example, for =arr = [2,3]=, the median is =(2 + 3) / 2 = 2.5=.

Implement the MedianFinder class:

- =MedianFinder()= initializes the =MedianFinder= object.
- =void addNum(int num)= adds the integer =num= from the data stream to the data structure.
- =double findMedian()= returns the median of all elements so far. Answers within =10=^{=-5=} of the actual answer will be accepted.



*Example 1:*

#+begin_example
Input
["MedianFinder", "addNum", "addNum", "findMedian", "addNum", "findMedian"]
[[], [1], [2], [], [3], []]
Output
[null, null, null, 1.5, null, 2.0]

Explanation
MedianFinder medianFinder = new MedianFinder();
medianFinder.addNum(1);    // arr = [1]
medianFinder.addNum(2);    // arr = [1, 2]
medianFinder.findMedian(); // return 1.5 (i.e., (1 + 2) / 2)
medianFinder.addNum(3);    // arr[1, 2, 3]
medianFinder.findMedian(); // return 2.0
#+end_example



*Constraints:*

- =-10=^{=5=}= <= num <= 10=^{=5=}
- There will be at least one element in the data structure before calling =findMedian=.
- At most =5 * 10=^{=4=} calls will be made to =addNum= and =findMedian=.

#+begin_src ruby
class MedianFinder
  def initialize
    @nums = []
  end

  def add_num(num)
    @nums.insert((@nums.bsearch_index { |x| x > num } || @nums.size), num)
  end

  def find_median
    size = @nums.size
    size.odd? ? @nums[size / 2] : (@nums[size / 2 - 1] + @nums[size / 2]) / 2.0
  end
end

#+end_src


*Follow up:*

- If all integer numbers from the stream are in the range =[0, 100]=, how would you optimize your solution?

- If =99%= of all integer numbers from the stream are in the range =[0, 100]=, how would you optimize your solution?

--------------

https://leetcode.cn/problems/find-median-from-data-stream/description/?envType=study-plan-v2&envId=top-interview-150
